services:
  cloud-config-server:
    container_name: docker-config-server
    build:
      context: .
      dockerfile: ./cloud-config-server/Dockerfile
    image: docker-config-server:latest
    expose:
      - 9296
    ports:
      - 9296:9296
    logging:
      driver: json-file
    depends_on:
      - service-registry
    networks:
      - spring-cloud-network
    links:
      - service-registry:service-registry
    hostname: 'cloud-config-server'
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/

  service-registry:
    container_name: docker-service-registry
    build:
      context: .
      dockerfile: ./service-registry/Dockerfile
    image: docker-service-registry:latest
    expose:
      - 8761
    ports:
      - 8761:8761
    logging:
      driver: json-file
    networks:
      - spring-cloud-network
    hostname: 'service-registry'

  cloud-gateway:
    container_name: docker-cloud-gateway
    build:
      context: .
      dockerfile: ./cloud-gateway/Dockerfile
    image: docker-cloud-gateway:latest
    expose:
      - 9093
    ports:
      - 9093:9093
    depends_on:
      - cloud-config-server
      - service-registry
    logging:
      driver: json-file
    networks:
      - spring-cloud-network
    links:
      - cloud-config-server:cloud-config-server
      - service-registry:service-registry
    hostname: 'cloud-gateway'
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - spring.cloud.config.uri=http://cloud-config-server:9296

  user-service:
    container_name: docker-user-service
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    image: docker-user-service:latest
    expose:
      - 9091
    ports:
      - 9091:9091
    depends_on:
      - cloud-config-server
      - service-registry
    logging:
      driver: json-file
    networks:
      - spring-cloud-network
    links:
      - cloud-config-server:cloud-config-server
      - service-registry:service-registry
    hostname: 'user-service'
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - spring.cloud.config.uri=http://cloud-config-server:9296

  medicinska-ustanova-service:
    container_name: docker-med-ust-service
    build:
      context: .
      dockerfile: ./medicinskaUstanova-service/Dockerfile
    image: docker-med-ust-service:latest
    expose:
      - 9090
    ports:
      - 9090:9090
    depends_on:
      - cloud-config-server
      - service-registry
      - gateway-api
    logging:
      driver: json-file
    networks:
      - spring-cloud-network
    links:
      - cloud-config-server:cloud-config-server
      - service-registry:service-registry
    hostname: 'med-ust-service'
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - spring.cloud.config.uri=http://cloud-config-server:9296
networks:
  spring-cloud-network:
    driver: bridge